### ISSUE TITLE
Can't sort external window using menu action

### ISSUE THREAD

**Issue by MarkJeronimus** [syllant/idea-plugin-linessorter#13]
When a file tab is in a separate window, the plugin cannot sort those tabs using the menu action.

*Steps to reproduce:*
1. Open two different files in tabs,
2. Drag one tab outside the main window,
3. When you have that external tab focused, go to menu (necessarily of the main window) Edit -> Sort lines.

*Expected behavior:*
It sorts the lines in the external tab.

*Actual behavior:*
As soon as the menu is clicked, the main window is focused, and the last focused tab in the main window is now focused too. It sorts that tab instead of the external tab.

*Possible workaround:*
Use a keyboard binding to sort the external document.

**Comment by krasa** [comment]
That is universal IntelliJ behaviour. Use a shortcut.

**Comment by syllant** [comment]
Thanks for the report, @MarkJeronimus, and thanks for the comment, @krasa. Closing this issue as I can't do anything easy to solve it.
