### ISSUE TITLE
Sorting is not handling "_" properly

### ISSUE THREAD

**Issue by elliotchance** [syllant/idea-plugin-linessorter#14]
Trying to sort these lines (which are already in order):

```
KOUNTA_GIFTCARD = "foo"
KOUNTA_GIFT_CARD = "bar"
```

Results in the reverse order:

```
KOUNTA_GIFT_CARD = "bar"
KOUNTA_GIFTCARD = "foo"
```

`_` greater than `C` and `c`.

**Comment by syllant** [comment]
Thanks for the report. This plugin relies on the default lexicographical order implemented in the JVM, and I want to keep the plugin minimalistic, without any extra option. I usually recommend the [String manipulation](https://plugins.jetbrains.com/plugin/2162-string-manipulation) plugin for more advanced usages, you may find the behavior you expect there.

Best,
Sylvain
