### ISSUE TITLE
Feature Request: Add option to remove duplicate lines

### ISSUE THREAD

**Issue by glen-edmonds** [syllant/idea-plugin-linessorter#15]
Almost all line sorting plugins have an option to remove duplicates.
(Actually this is the first I've encountered that doesn't have it).

**Comment by syllant** [comment]
This plugin has the minimal scope. As mentioned in the home page, please use more advanced plugins for a broader scope, like https://plugins.jetbrains.com/plugin/2162-string-manipulation/ 😉
