### ISSUE TITLE
Support to sort JSON

### ISSUE THREAD

**Issue by bennycode** [syllant/idea-plugin-linessorter#16]
Hi @syllant, I am the co-author of [Sort JSON](https://sortjson.com/) and I am using your [Lines Sorter plugin](https://plugins.jetbrains.com/plugin/5919-lines-sorter) very much. Can you add the functionality to sort JSON? I often find myself in need to sort all JSON properties in WebStorm.

Here is an example of the source:

```json
{
  "name": "@bennycode/my-package",
  "version": "1.1.2",
  "description": "Calculates the average.",
  "main": "index.js",
  "scripts": {
    "build": "tsc",
    "tscinit": "tsc --init",
    "prebenny": "echo before benny",
    "benny": "echo benny",
    "pretest": "echo before test",
    "test": "node getAverage.test.js",
    "posttest": "echo after test"
  },
  "author": "bennycode",
  "license": "MIT",
  "dependencies": {
    "ml-array-max": "1.x"
  },
  "devDependencies": {
    "typescript": "4.4.x"
  }
}
```

I would like to mark all the lines in WebStorm and sort them using your plugin like this:

```json

{
  "author": "bennycode",
  "dependencies": {
    "ml-array-max": "1.x"
  },
  "description": "Calculates the average.",
  "devDependencies": {
    "typescript": "4.4.x"
  },
  "license": "MIT",
  "main": "index.js",
  "name": "@bennycode/my-package",
  "scripts": {
    "benny": "echo benny",
    "build": "tsc",
    "posttest": "echo after test",
    "prebenny": "echo before benny",
    "pretest": "echo before test",
    "test": "node getAverage.test.js",
    "tscinit": "tsc --init"
  },
  "version": "1.1.2"
}
```

Can you add this feature please?

**Comment by syllant** [comment]
Hey, your suggestion makes total sense, smart sorting would apply to lots of other cases too (XML, YAML, etc.), but I don't want to add any intelligence nor option to this plugin, I want to keep it focused on the basic need (until it becomes a native feature). Richer plugins such as [String Manipulation](https://github.com/krasa/StringManipulation) might be a better fit for your suggestion, I'd recommend that your reach out to them.

**Comment by krasa** [comment]
Freshly implemented here, you can try it: https://github.com/krasa/StringManipulation/issues/151

**Comment by bennycode** [comment]
Thanks for the fast feedback! 

@syllant if you don't mind I will take your code and add JSON sorting to it. Since your code is licensed under [WTFPL](https://de.wikipedia.org/wiki/WTFPL) this shouldn't be a problem.

@krasa your [JsonSort](https://github.com/krasa/StringManipulation/blob/master/src/osmedile/intellij/stringmanip/sort/support/JsonSort.java) class accepts a list of Strings which is exactly what I need to pair it up with [SortUtils.defaultSort](https://github.com/syllant/idea-plugin-linessorter/blob/1.0/src/org/sylfra/idea/plugins/linessorter/SortAction.java#L62). Given the idea that I am building a new plugin, what would be the best way to consume your code? Can I integrate it through Maven?

**Comment by syllant** [comment]
@bennycode Sure, feel free to fork the plugin 👍 Although I'm curious, why do you want to introduce another plugin rather than relying on `String Manipulation`, since it just introduced the feature you wanted?

**Comment by bennycode** [comment]
> why do you want to introduce another plugin rather than relying on `String Manipulation`

I like the simplicity of your plugin. Looking at "StringManipulation" it doesn't look like I can simply sort columns by hitting Alt + Shift + L, or can I? @krasa 

**Screenshot of StringManipulation:**

![image](https://user-images.githubusercontent.com/469989/150181087-6ebcdd1f-cfcb-4ad8-8464-7644f5ba6578.png)

**Comment by krasa** [comment]
You should use Gradle, it supports dependencies https://github.com/krasa/StringManipulation-Localization/blob/f3f4696efea39ff9f9e2a7cbe64d976de455d959/gradle.properties#L16

But I do not have any stable API, the best would be to just copy-paste the code. 

I fixed Json sort, it does not need a dialog, but aligning does not have any standard usecase imho, so there is only the generic one.

**Comment by bennycode** [comment]
> the best would be to just copy-paste the code

Your code is distributed under Apache License 2.0. Can I just copy your sources into my repo by adding a copyright in the header of that file? Or what's the best way to integrate your code?

Can you maybe export an API for using your code? Modular code would help very much with making it useful for other purposes. 😊

**Comment by krasa** [comment]
Sure, just copy it and don't worry about it. 

It is a super rare request, and I do not produce a perfect code, rather a good enough one and then polish it as needed. So I do not think it is worth it.

**Comment by krasa** [comment]
I've been experimenting with remembering settings so that repeat action does not show a dialog, and it would be possible to even save it as an extra custom action. Would that solve your problem?

**Comment by bennycode** [comment]
Hey @krasa, thank you very much for offering your help. Adding a memory function to your plugin is maybe a good idea but can also get confusing as a user if you are not sure which function of [String Manipulation](https://plugins.jetbrains.com/plugin/18291-string-manipulation--localization/) you have been using last. It also carries the question about a suitable hotkey.

I am a power user of [Lines Sorter](https://plugins.jetbrains.com/plugin/5919-lines-sorter) and got used to hitting "Alt" + "Shift" + "L" on my keyboard for years. That's why I wanted to keep the plugin as-is and just equip it with a function to sort JSON.

@syllant made clear that he wants to keep his plugin to do one thing well (like [Unix programs](https://en.wikipedia.org/wiki/Unix_philosophy)), so I created my own plugin on top of "Lines Sorter" and called it [**Lines Sorter Plus**](https://plugins.jetbrains.com/plugin/18564-lines-sorter-plus) as it does the same thing **plus** sorting JSON. 😁

It was a good opportunity to refresh my rusty Java skills.

Thanks a lot to the both of you for walking through some ideas with me. 🙏 

Now that I have what I wanted, I can close this topic. You can find my code here: https://github.com/bennycode/linessorterplus/
