### ISSUE TITLE
remove duplicate lines

### ISSUE THREAD

**Issue by nickleus** [syllant/idea-plugin-linessorter#4]
+1

i remember TextPad on windows had this functionality and it was super great to have! :)

**Comment by syllant** [comment]
Hi,

I'd like to keep this plugin as simple as possible at this time. I would suggest to use the *String Manipulation* plugin to remove duplicate lines.

Thanks

**Comment by nickleus** [comment]
@syllant thx! works great!

**Comment by krasa** [comment]
already implemented in [String Manipulation plugin](https://plugins.jetbrains.com/plugin/2162)
