### ISSUE TITLE
Suggestion: sort lines based on columns or regex.

### ISSUE THREAD

**Issue by Trinition** [syllant/idea-plugin-linessorter#5]
I made a similar suggestion for the atom 'lines' plugin...

I often need to sort lines, but not based on the entire value of the line, but just a portion of the line.  For example consider this list of names and ages:

```
John Smith  22
Sally Smith 20
John Public 35
```

If I could sort using the values starting at column 12 (or, more specifically, columns 12-13), then I could sort by ages.

What's more, I often encounter text that isn't neatly formatted into columns.  For example:

```
name="John Smith", age=22
name="Sally Smith", age=20
name="John Q. Public", age=35
```

In such a case, being able to use a RegEx to extract the group to sort by would be very powerful.  For example, the RegEx /age=(\d+)/ would allow put the age value into group 1 ($1) which would then be sorted upon.

**Comment by krasa** [comment]
[String Manipulation ](https://plugins.jetbrains.com/plugin/2162) supports line sorting by subselection.

**Comment by syllant** [comment]
Closing this issue, please use [String Manipulation ](https://plugins.jetbrains.com/plugin/2162) for more advanced usages
