### ISSUE TITLE
" vs '

### ISSUE THREAD

**Issue by aronduby** [syllant/idea-plugin-linessorter#7]
I wish it could treat ' and " as the same for sorting. If I have a large file of import statements and some are using " and others ' it sorts all of the " before all of the '. Technically that's correct, but I feel like this is something that when sorting should be interchangable. Maybe add ` to that list as well?

Idealy it would be great to not have mixed quotation usage, but... ya know

**Comment by syllant** [comment]
This makes sense. Actually, my initial goal was to add some contextual intelligence to the sort, which would include your use case (my own need was about sorting list of nodes in XML files, which should move the inner content of nodes too).

But it's unlikely I change the scope of this plugin now, you could try with https://github.com/krasa/StringManipulation, which is more ambitious.
