### ISSUE TITLE
Date sorting sorts based on day instead of month

### ISSUE THREAD

**Issue by toubou91** [syllant/idea-plugin-linessorter#9]
Hello,

really nice effort.

However, the default sorting sorts date text based on the date, instead of month:

```
"03/11",
"03/12",
"04/01",
"04/02",
"04/03",
"04/04",
"04/05",
"04/06",
"04/07",
"04/08",
"05/02"
```

Is this something we could improve?

I can help with that if you want.

Regards,
Thodoris

**Comment by syllant** [comment]
Hi Thodoris,

I don't want to make this plugin more advanced, other plugins are more ambitious and more active (e.g. [String Manipulation](https://plugins.jetbrains.com/plugin/2162-string-manipulation)).

However, note that your need is not so obvious. E.g. nothing in your example indicates that the lines correspond to dates, and that the month is the second number. So the plugin would need another input (dedicated action, contextual knowledge, etc.) to do what you want without too many false positives.

Best
Sylvain
